$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:2
        },
        400:{
            items:2
        },
        600:{
            items:3
        },
        1000:{
            items:4
        },
        1500:{
            items:6
        },
        2000:{
            items:8
        }
    }
})